graph LR;
    note Input Image;
    style input Image fill:#fff;
    text-align: left;

    A[Conv2d] -> B[MaxPool];
    style Conv2d fill:#000,stroke-width:2px;
    style MaxPool fill:#000,stroke-width:2px;

    B -> C[Conv2d];
    style Conv2d fill:#000,stroke-width:2px;

    C -> D[MaxPool];
