classDiagram;
    class InputImage
    class Conv2d_1x1
    class MaxPool2
    class InceptionV3
    class Conv2d_3x3
    class InceptionBlock
    class InceptionV3 Block(3)
    class InceptionV3 Block(4)
    class InceptionV3 Block(5)
    class InceptionV3 Block(6)

    InputImage -->|-> Conv2d_1x1
    Conv2d_1x1 -->|-> MaxPool2
    MaxPool2 -->|-> InceptionV3
    InceptionV3 -->|-> InceptionBlock
    InceptionBlock -->|-> InceptionV3 Block(3)
    InceptionV3 Block(3) -->|-> Conv2d_3x3
    Conv2d_3x3 -->|-> InceptionBlock
    InceptionBlock -->|-> InceptionV3 Block(4)
    InceptionV3 Block(4) -->|-> Conv2d_3x3
    Conv2d_3x3 -->|-> InceptionBlock
    InceptionBlock -->|-> InceptionV3 Block(5)
    InceptionV3 Block(5) -->|-> Conv2d_3x3
    Conv2d_3x3 -->|-> InceptionBlock
    InceptionBlock -->|-> InceptionV3 Block(6)
